CREATE TABLE TB_TOURIST(
	TOURIST_ID NUMBER PRIMARY KEY,
	TOURIST_NAME NVARCHAR2(30) NOT NULL,
	TOURIST_NO VARCHAR2(15) NOT NULL,
	PHONE VARCHAR2(13),
	DESTINATION NVARCHAR2(30),
	ENROLL_DATE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE SEQ_TOURIST_ID;
NOCACHE;

INSERT 
  INTO 
       TB_TOURIST
VALUES (
       SEQ_TOURIST_ID.NEXTVAL
     , '김윤기대표님'
     , '961104-1234567'
     , '010-3153-1234'
     , ''
     , SYSDATE);

SELECT * FROM TB_TOURIST;

DROP TABLE TB_TOURIST;
